### ISSUE TITLE
what is promoter.resources.linstor

### ISSUE THREAD

**Issue by meilihao** [LINBIT/linbit-documentation#28]
what is [`promoter.resources.linstor`](https://github.com/LINBIT/linbit-documentation/blob/master/UG9/en/administration-linstor.adoc#managing-the-services)?

I found that ha configuration failed, drbdd log:
```log
'linstor' not defined in your config (for this host)
WARN [drbdd::plugin::promoter] promoter: 'drbdadmin adjust linstor' did not return successfully.
...
```

**Comment by rck** [comment]
it is supposed to be the name of a DRBD resource. The resource was named "linstor" in a first draft, but got renamed to "linstor_db" for more clarity. I overlooked the name in this place. Fixed in: https://github.com/LINBIT/linbit-documentation/commit/94f4e7e21eac66382ec4b558d1c58c18b44d5a51

thanks for spotting this!
